# Generated by Django 2.0.5 on 2018-06-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gaupalika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('risk_rating', models.CharField(blank=True, max_length=256)),
                ('high_risk_ok', models.CharField(blank=True, max_length=256)),
                ('direct_risk_for', models.CharField(blank=True, max_length=256)),
                ('potential_impact', models.CharField(blank=True, max_length=256)),
                ('probability_of_risk', models.CharField(blank=True, max_length=256)),
                ('mitigation_work_by', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.District')),
                ('gaupalika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Gaupalika')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('land_size', models.IntegerField(blank=True, default=None, null=True)),
                ('eligibility_source', models.CharField(blank=True, max_length=256)),
                ('total_male', models.IntegerField(blank=True, default=None, null=True)),
                ('total_female', models.IntegerField(blank=True, default=None, null=True)),
                ('men_0_5', models.IntegerField(blank=True, default=None, null=True)),
                ('men_6_18', models.IntegerField(blank=True, default=None, null=True)),
                ('men_19_60', models.IntegerField(blank=True, default=None, null=True)),
                ('men_60_plus', models.IntegerField(blank=True, default=None, null=True)),
                ('women_0_5', models.IntegerField(blank=True, default=None, null=True)),
                ('women_6_18', models.IntegerField(blank=True, default=None, null=True)),
                ('women_19_60', models.IntegerField(blank=True, default=None, null=True)),
                ('women_60_plus', models.IntegerField(blank=True, default=None, null=True)),
                ('other', models.IntegerField(blank=True, default=None, null=True)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.District')),
                ('gaupalika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Gaupalika')),
                ('geopoint', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.GeoPoint')),
                ('geosite', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.GeoSite')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Place'),
        ),
        migrations.AddField(
            model_name='household',
            name='ward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Ward'),
        ),
        migrations.AddField(
            model_name='geosite',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Place'),
        ),
        migrations.AddField(
            model_name='geosite',
            name='ward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Ward'),
        ),
    ]
