# Generated by Django 2.0.5 on 2018-06-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20180620_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaupalika',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='metadata.District'),
            preserve_default=False,
        ),
    ]
