# Generated by Django 2.0.5 on 2018-07-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20180711_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='geopoint',
        ),
        migrations.AddField(
            model_name='geosite',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='geosite',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='GeoPoint',
        ),
    ]
