# Generated by Django 2.0.5 on 2018-07-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20180711_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
        migrations.RemoveField(
            model_name='gaupalika',
            name='code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='code',
        ),
    ]
