# Generated by Django 2.0.5 on 2018-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated_at',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
