# Generated by Django 2.0.5 on 2018-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='default_object',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
