# Generated by Django 2.0.5 on 2018-07-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20180615_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='default_object',
        ),
    ]
